<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_First Name_customer.firstName</name>
   <tag></tag>
   <elementGuidId>cf6474a5-e652-4190-bd22-7985a035446c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='customer.firstName']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>9cffeb6b-eff9-419e-bb92-e475c643bd8d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>customer.firstName</value>
      <webElementGuid>4d08fe8d-e648-4ed5-ae3f-bfd84f49b309</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>customer.firstName</value>
      <webElementGuid>1ffcbd6d-21b1-4020-9f06-be34d8fddb61</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>27f8f296-8717-4d75-9832-9ad08c2729cd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>2bd44282-5d81-49ec-90ef-15be0f603316</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;customer.firstName&quot;)</value>
      <webElementGuid>39764045-f9f1-4d2b-8919-4fc7669641be</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='customer.firstName']</value>
      <webElementGuid>02f3a7e7-8224-42f3-a69d-2f10fa0fff6f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='customerForm']/table/tbody/tr/td[2]/input</value>
      <webElementGuid>af487481-27fc-4099-849c-75f014190e9b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[2]/input</value>
      <webElementGuid>c968e8e7-de73-42ae-9303-67212bf04d4b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'customer.firstName' and @name = 'customer.firstName' and @type = 'text']</value>
      <webElementGuid>285952a0-b9c5-46b4-b535-26f99f2ac688</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
